# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-vcs-permalinks
  - id: debug-statements
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: no-commit-to-branch
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.5
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
