language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'
  - DJANGO_VERSION='Django>=1.10,<2.0'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.7,<1.8'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.3"
      env: DJANGO_VERSION='Django>=1.10,<2.0'
    - python: "3.3"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO_VERSION='Django>=1.7,<1.8'
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_script:
  - pip install -U pip
  - pip install -U tox
  - pip install codecov
  - pip install $DJANGO_VERSION
  - pip install -r tests/requirements.txt

script:
  - coverage run manage.py test --settings=tests.settings
  - coverage report
  - flake8
  - isort --recursive --check-only osm_field tests

after_success:
    codecov
