language: python

python: 3.5

env:
  - TOXENV=py27-dj17
  - TOXENV=py33-dj17
  - TOXENV=py34-dj17
  - TOXENV=py33-dj18
  - TOXENV=py27-dj18
  - TOXENV=py27-dj19
  - TOXENV=py27-dj110
  - TOXENV=py34-dj18
  - TOXENV=py34-dj19
  - TOXENV=py34-dj110
  - TOXENV=py35-dj18
  - TOXENV=py35-dj19
  - TOXENV=py35-dj110
  - TOXENV=py27-djmaster
  - TOXENV=py34-djmaster
  - TOXENV=py35-djmaster
  - TOXENV=flake8
  - TOXENV=isort

install:
  - pip install -U pip
  - pip install -U tox
  - pip install codecov

script:
  - tox -e ${TOXENV}

matrix:
  allow_failures:
    - env: TOXENV=py27-djmaster
    - env: TOXENV=py34-djmaster
    - env: TOXENV=py35-djmaster

after_success:
    codecov
