language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=stable/1.8.x
  - DJANGO=stable/1.9.x
  - DJANGO=master

install:
  - pip install https://github.com/django/django/archive/${DJANGO}.tar.gz
  - pip install -e .
  - pip install coveralls django-discover-runner flake8

script:
  - flake8 osm_field --ignore=E128,E501
  - coverage run `which django-admin.py` test -v 2 --pythonpath=./ --settings=tests.settings tests
  - coverage xml
  - coverage report -m

after_success:
    coveralls
