language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=stable/1.7.x
  - DJANGO=stable/1.8.x
  - DJANGO=stable/1.9.x
  - DJANGO=stable/1.10.x
  - DJANGO=master

install:
  - pip install https://github.com/django/django/archive/${DJANGO}.tar.gz
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install codecov

script:
  - flake8
  - isort --recursive --check-only
  - coverage run `which django-admin.py` test -v 2 --pythonpath=./ --settings=tests.settings
  - coverage report -m

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=stable/1.9.x
    - python: "3.3"
      env: DJANGO=stable/1.10.x
    - python: "3.3"
      env: DJANGO=master

    - python: "3.5"
      env: DJANGO=stable/1.7.x

  allow_failures:
    - env: DJANGO=master

after_success:
    codecov
