language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=stable/1.4.x
  - DJANGO=stable/1.5.x
  - DJANGO=stable/1.6.x
  - DJANGO=stable/1.7.x
  - DJANGO=master

install:
  - pip install https://github.com/django/django/archive/${DJANGO}.tar.gz
  - pip install -e .
  - pip install coveralls django-discover-runner flake8

script:
  - flake8 osm_field --ignore=E128,E501
  - coverage run `which django-admin.py` test -v 2 --pythonpath=./ --settings=tests.settings tests
  - coverage xml
  - coverage report -m

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=stable/1.4.x
    - python: "3.4"
      env: DJANGO=stable/1.4.x

    - python: "3.4"
      env: DJANGO=stable/1.5.x

    - python: "3.4"
      env: DJANGO=stable/1.6.x

after_success:
    coveralls
