[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=5,<6"]

[tool.black]
target-version = ['py38']

[tool.coverage.run]
branch = true
source = ["osm_field/"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[tool.isort]
combine_as_imports = true
known_first_party = ["osm_field", "tests"]
profile = "black"

[tool.setuptools_scm]
